application: cam-ar
version: 1

runtime: python27
api_version: 1

threadsafe: yes

handlers:
- url: /resources
  static_dir: resources
- url: /.*
  script: main.app
  secure: always

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?\@docs/.*$
- ^(.*/)?.*\.scss$
